spring:
  profiles:
    # 默认使用单数据源环境 需要禁用掉配置类：MultipleDataSourceConfig
    active: dynamic
  thymeleaf:
  # 禁用缓存
    cache: false
  messages:
    # 指定国际化文件路径
    basename: i18n.login
mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mapping/*/*.xml
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  # 动态数据源 autoRuntimeDialect:true，确保使用不同数据源时，会使用匹配的分页进行查询
#  auto-runtime-dialect: true
logging:
  file:
    # 指定日志生成位置
    path: ../logs/springboot2example

#指定异步任务线程池配置信息
executor:
  pool:
    core:
      size: 10
    max:
      size: 200
  queue:
    capacity: 2000

