spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: m1,s1
      m1:
        type: com.alibaba.druid.pool.DruidDataSource
        #   数据源基本配置
        url: jdbc:mysql://127.0.0.1:6001/management0929?allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root
        # 初始化连接数
        initialSize: 1
        # 连接池最小空闲
        minIdle: 1
        # 连接池最大使用连接数量
        maxActive: 20
        # 获取连接最大等待时间
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 如果用Oracle，则把poolPreparedStatements配置为true，mysql可以配置为false
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 20
        #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
      s1:
        type: com.alibaba.druid.pool.DruidDataSource
        #   数据源基本配置
        url: jdbc:mysql://127.0.0.1:6003/management0929?allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root
        # 初始化连接数
        initialSize: 1
        # 连接池最小空闲
        minIdle: 1
        # 连接池最大使用连接数量
        maxActive: 20
        # 获取连接最大等待时间
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 如果用Oracle，则把poolPreparedStatements配置为true，mysql可以配置为false
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 20
        #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
    masterslave:
      load-balance-algorithm-type: round_robin
    sharding:
      master-slave-rules:
        ds:
          master-data-source-name: m1
          slave-data-source-names: s1
      default-data-source-name: ds
    props:
      sql:
        show: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        #连接池最大连接数（负值表示没有限制）默认8
        max-active: 100
        #连接池中最大空闲连接 默认8
        max-idle: 8
        #连接池中最小空闲连接 默认0
        min-idle: 0